package com.example.yangyongwen.meituantestdemo.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NEWS".
 */
public class News {

    private Long publish_time;
    private String title;
    private String content;
    private Float value;

    public News() {
    }

    public News(Long publish_time) {
        this.publish_time = publish_time;
    }

    public News(Long publish_time, String title, String content, Float value) {
        this.publish_time = publish_time;
        this.title = title;
        this.content = content;
        this.value = value;
    }

    public Long getPublish_time() {
        return publish_time;
    }

    public void setPublish_time(Long publish_time) {
        this.publish_time = publish_time;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Float getValue() {
        return value;
    }

    public void setValue(Float value) {
        this.value = value;
    }

}
